[package]
name = "minimp4"
version = "0.1.0"
authors = ["DarkSky"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.minimp4-sys]
path = "minimp4-sys"
