[package]
authors = ["DarkSky"]
categories = ["external-ffi-bindings"]
description = "A minimp4 ffi binding"
edition = "2021"
homepage = "https://github.com/darkskygit/minimp4.rs"
include = [
  "src/**/*",
  "build.rs",
  "minimp4.*",
  "Cargo.toml",
  "README.md",
  "LICENSE",
]
keywords = ["minimp4", "ffi", "bindings"]
license = "MPL-2.0"
name = "minimp4-sys"
readme = "README.md"
repository = "https://github.com/darkskygit/minimp4.rs"
version = "0.1.1"

[build-dependencies]
bindgen = "0.69.4"
cc      = { version = "1.0.99", features = ["parallel"] }
